title: "Visal So"
author: "Visal So"
description: "Ph.D. candidate in Physics at Rice University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false            # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "About Me", sidebaricon: home}
  - {url: "/CV.pdf", title: "CV", sidebaricon: address-card}
  - {file: "publications.md", title: "Publications", sidebaricon: address-card}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:vs39@rice.edu"}
  - {title: Github, icon: github, url: "https://github.com/visalso"}
  - {title: Google scholar, icon: graduation-cap, url: "https://scholar.google.com/citations?user=hl-oGi4AAAAJ&hl=en"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
